language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-xdist pytest-cov
  - pip install .
script:
  - py.test --boxed tests/ -vvvvs
addons:
  apt:
    packages:
     - graphviz
